Introdução a Python
-------------------

És nova na Python? Vamos configurar apropriadamente o teu ambiente da Python:

.. toctree::
   :maxdepth: 2

   starting/which-python

- Instalar apropriadamente a Python no teu sistema:

 .. toctree::
    :maxdepth: 1

    starting/installation
    starting/install3/osx
    starting/install3/win
    starting/install3/linux
    starting/install/osx
    starting/install/win
    starting/install/linux


- Usar ambientes virtuais com a Pipenv:

 .. toctree::
    :maxdepth: 2

    dev/virtualenvs


Ambientes de Desenvolvimento da Python
--------------------------------------

Esta parte do guia foca-se no ambiente de desenvolvimento da Python, e as ferramentas de boas práticas que estão disponíveis para escrita de código de Python.

.. toctree::
   :maxdepth: 2

   dev/env
   dev/virtualenvs
   dev/pip-virtualenv




Escrita de Código de Python Excelente
-------------------------------------

Esta parte do guia foca-se nas boas práticas para escrita de código de Python.

.. toctree::
   :maxdepth: 2

   writing/structure
   writing/style
   writing/reading
   writing/documentation
   writing/tests
   writing/logging
   writing/gotchas
   writing/license



Guia de Cenário para Aplicações de Python
-----------------------------------------

Esta parte do guia foca-se na ferramenta e conselho de módulo baseado nos diferentes cenários.

.. toctree::
   :maxdepth: 2

   scenarios/client
   scenarios/web
   scenarios/scrape
   scenarios/cli
   scenarios/gui
   scenarios/db
   scenarios/network
   scenarios/admin
   scenarios/ci
   scenarios/speed
   scenarios/scientific
   scenarios/imaging
   scenarios/serialization
   scenarios/xml
   scenarios/json
   scenarios/crypto
   scenarios/ml
   scenarios/clibs


Entrega de Código de Python Excelente
--------------------------------------

Esta parta do guia foca-se na partilha e implementação em produção do teu código de Python.

.. toctree::
   :maxdepth: 2

   shipping/publishing
   shipping/packaging
   shipping/freezing


Notas Adicionais
----------------

Esta parte do guia, que é na sua maioria prosa, começa com alguma informação de fundo sobre a Python, e depois foca-se nos próximos passos.

.. toctree::
   :maxdepth: 2

   intro/duction
   intro/community
   intro/learning
   intro/documentation
   intro/news

.. note::
   Notas definidas dentro de todas escalas musicais diatónicas e cromáticas foram intencionalmente excluídas desta lista de notas adicionais. Adicionalmente, esta nota.


--------------------------------------

Notas de contribuição e informação legal (para aqueles interessados).

.. toctree::
   :maxdepth: 2

   notes/contribute
   notes/license
   notes/styleguide
